alter table public.niche_heros
  add column if not exists group_name text,
  add column if not exists hero_type text not null default 'subnicho',
  add column if not exists slug text;

create index if not exists niche_heros_group_name_idx on public.niche_heros (group_name);
create index if not exists niche_heros_hero_type_idx on public.niche_heros (hero_type);
create index if not exists niche_heros_slug_idx on public.niche_heros (slug);

insert into public.niche_heros (niche_name, group_name, hero_type, theme, slug, sort_order, active)
values
  ('Visão geral para negócios', 'Geral', 'principal', 'clean', 'visao-geral-para-negocios', 0, true),
  ('Profissionais da Saúde', 'Profissionais da Saúde', 'grupo', 'medical', 'profissionais-da-saude', 100, true),
  ('Médico', 'Profissionais da Saúde', 'subnicho', 'medical', 'medico', 101, true),
  ('Cardiologista', 'Profissionais da Saúde', 'subnicho', 'medical', 'cardiologista', 102, true),
  ('Dermatologista', 'Profissionais da Saúde', 'subnicho', 'medical', 'dermatologista', 103, true),
  ('Dentista', 'Profissionais da Saúde', 'subnicho', 'medical', 'dentista', 104, true),
  ('Fisioterapeuta', 'Profissionais da Saúde', 'subnicho', 'medical', 'fisioterapeuta', 105, true),
  ('Nutricionista', 'Profissionais da Saúde', 'subnicho', 'medical', 'nutricionista', 106, true),
  ('Psicólogo', 'Profissionais da Saúde', 'subnicho', 'medical', 'psicologo', 107, true),
  ('Fonoaudiólogo', 'Profissionais da Saúde', 'subnicho', 'medical', 'fonoaudiologo', 108, true),
  ('Bem-estar & Terapias', 'Bem-estar & Terapias', 'grupo', 'health', 'bem-estar-terapias', 200, true),
  ('Terapeuta', 'Bem-estar & Terapias', 'subnicho', 'health', 'terapeuta', 201, true),
  ('Psicanalista', 'Bem-estar & Terapias', 'subnicho', 'health', 'psicanalista', 202, true),
  ('Massoterapeuta', 'Bem-estar & Terapias', 'subnicho', 'health', 'massoterapeuta', 203, true),
  ('Reiki', 'Bem-estar & Terapias', 'subnicho', 'health', 'reiki', 204, true),
  ('Yoga', 'Bem-estar & Terapias', 'subnicho', 'health', 'yoga', 205, true),
  ('Pilates', 'Bem-estar & Terapias', 'subnicho', 'health', 'pilates', 206, true),
  ('Clínica de bem-estar', 'Bem-estar & Terapias', 'subnicho', 'health', 'clinica-de-bem-estar', 207, true),
  ('Fitness & Esporte', 'Fitness & Esporte', 'grupo', 'fitness', 'fitness-esporte', 300, true),
  ('Personal Trainer', 'Fitness & Esporte', 'subnicho', 'fitness', 'personal-trainer', 301, true),
  ('Academia', 'Fitness & Esporte', 'subnicho', 'fitness', 'academia', 302, true),
  ('Crossfit', 'Fitness & Esporte', 'subnicho', 'fitness', 'crossfit', 303, true),
  ('Treinador esportivo', 'Fitness & Esporte', 'subnicho', 'fitness', 'treinador-esportivo', 304, true),
  ('Estúdio funcional', 'Fitness & Esporte', 'subnicho', 'fitness', 'estudio-funcional', 305, true),
  ('Assessoria de corrida', 'Fitness & Esporte', 'subnicho', 'fitness', 'assessoria-de-corrida', 306, true),
  ('Marketing & Criativos', 'Marketing & Criativos', 'grupo', 'agency', 'marketing-criativos', 400, true),
  ('Agência de Marketing', 'Marketing & Criativos', 'subnicho', 'agency', 'agencia-de-marketing', 401, true),
  ('Social Media', 'Marketing & Criativos', 'subnicho', 'agency', 'social-media', 402, true),
  ('Designer', 'Marketing & Criativos', 'subnicho', 'agency', 'designer', 403, true),
  ('Gestor de Tráfego', 'Marketing & Criativos', 'subnicho', 'agency', 'gestor-de-trafego', 404, true),
  ('Produtora de Vídeo', 'Marketing & Criativos', 'subnicho', 'agency', 'produtora-de-video', 405, true),
  ('Fotógrafo', 'Marketing & Criativos', 'subnicho', 'agency', 'fotografo', 406, true),
  ('Web Designer', 'Marketing & Criativos', 'subnicho', 'agency', 'web-designer', 407, true),
  ('Comércio & Varejo', 'Comércio & Varejo', 'grupo', 'retail', 'comercio-varejo', 500, true),
  ('Loja de Roupas', 'Comércio & Varejo', 'subnicho', 'retail', 'loja-de-roupas', 501, true),
  ('Calçados', 'Comércio & Varejo', 'subnicho', 'retail', 'calcados', 502, true),
  ('Boutique', 'Comércio & Varejo', 'subnicho', 'retail', 'boutique', 503, true),
  ('Supermercado', 'Comércio & Varejo', 'subnicho', 'retail', 'supermercado', 504, true),
  ('Ótica', 'Comércio & Varejo', 'subnicho', 'retail', 'otica', 505, true),
  ('Papelaria', 'Comércio & Varejo', 'subnicho', 'retail', 'papelaria', 506, true),
  ('Pet Shop', 'Comércio & Varejo', 'subnicho', 'retail', 'pet-shop', 507, true),
  ('Loja de Móveis', 'Comércio & Varejo', 'subnicho', 'retail', 'loja-de-moveis', 508, true),
  ('Alimentação', 'Alimentação', 'grupo', 'food', 'alimentacao', 600, true),
  ('Restaurante', 'Alimentação', 'subnicho', 'food', 'restaurante', 601, true),
  ('Hamburgueria', 'Alimentação', 'subnicho', 'food', 'hamburgueria', 602, true),
  ('Pizzaria', 'Alimentação', 'subnicho', 'food', 'pizzaria', 603, true),
  ('Padaria', 'Alimentação', 'subnicho', 'food', 'padaria', 604, true),
  ('Cafeteria', 'Alimentação', 'subnicho', 'food', 'cafeteria', 605, true),
  ('Doceria', 'Alimentação', 'subnicho', 'food', 'doceria', 606, true),
  ('Marmitaria', 'Alimentação', 'subnicho', 'food', 'marmitaria', 607, true),
  ('Delivery', 'Alimentação', 'subnicho', 'food', 'delivery', 608, true),
  ('Beleza & Estética', 'Beleza & Estética', 'grupo', 'beauty', 'beleza-estetica', 700, true),
  ('Clínica de Estética', 'Beleza & Estética', 'subnicho', 'beauty', 'clinica-de-estetica', 701, true),
  ('Salão de Beleza', 'Beleza & Estética', 'subnicho', 'beauty', 'salao-de-beleza', 702, true),
  ('Barbearia', 'Beleza & Estética', 'subnicho', 'beauty', 'barbearia', 703, true),
  ('Manicure', 'Beleza & Estética', 'subnicho', 'beauty', 'manicure', 704, true),
  ('Maquiadora', 'Beleza & Estética', 'subnicho', 'beauty', 'maquiadora', 705, true),
  ('Esteticista', 'Beleza & Estética', 'subnicho', 'beauty', 'esteticista', 706, true),
  ('Micropigmentação', 'Beleza & Estética', 'subnicho', 'beauty', 'micropigmentacao', 707, true),
  ('Serviços Profissionais', 'Serviços Profissionais', 'grupo', 'clean', 'servicos-profissionais', 800, true),
  ('Consultor', 'Serviços Profissionais', 'subnicho', 'clean', 'consultor', 801, true),
  ('Contador', 'Serviços Profissionais', 'subnicho', 'clean', 'contador', 802, true),
  ('Corretor de Seguros', 'Serviços Profissionais', 'subnicho', 'clean', 'corretor-de-seguros', 803, true),
  ('Engenheiro', 'Serviços Profissionais', 'subnicho', 'clean', 'engenheiro', 804, true),
  ('Arquiteto', 'Serviços Profissionais', 'subnicho', 'clean', 'arquiteto', 805, true),
  ('Prestador de Serviço', 'Serviços Profissionais', 'subnicho', 'clean', 'prestador-de-servico', 806, true),
  ('Empresa B2B', 'Serviços Profissionais', 'subnicho', 'clean', 'empresa-b2b', 807, true),
  ('Jurídico', 'Jurídico', 'grupo', 'legal', 'juridico', 900, true),
  ('Advogado', 'Jurídico', 'subnicho', 'legal', 'advogado', 901, true),
  ('Escritório de Advocacia', 'Jurídico', 'subnicho', 'legal', 'escritorio-de-advocacia', 902, true),
  ('Advogado Trabalhista', 'Jurídico', 'subnicho', 'legal', 'advogado-trabalhista', 903, true),
  ('Advogado Previdenciário', 'Jurídico', 'subnicho', 'legal', 'advogado-previdenciario', 904, true),
  ('Advogado Empresarial', 'Jurídico', 'subnicho', 'legal', 'advogado-empresarial', 905, true),
  ('Construção & Casa', 'Construção & Casa', 'grupo', 'construction', 'construcao-casa', 1000, true),
  ('Construtora', 'Construção & Casa', 'subnicho', 'construction', 'construtora', 1001, true),
  ('Reformas', 'Construção & Casa', 'subnicho', 'construction', 'reformas', 1002, true),
  ('Gesso', 'Construção & Casa', 'subnicho', 'construction', 'gesso', 1003, true),
  ('Marcenaria', 'Construção & Casa', 'subnicho', 'construction', 'marcenaria', 1004, true),
  ('Serralheria', 'Construção & Casa', 'subnicho', 'construction', 'serralheria', 1005, true),
  ('Elétrica', 'Construção & Casa', 'subnicho', 'construction', 'eletrica', 1006, true),
  ('Energia Solar', 'Construção & Casa', 'subnicho', 'construction', 'energia-solar', 1007, true),
  ('Paisagismo', 'Construção & Casa', 'subnicho', 'construction', 'paisagismo', 1008, true),
  ('Automotivo', 'Automotivo', 'grupo', 'auto', 'automotivo', 1100, true),
  ('Oficina Mecânica', 'Automotivo', 'subnicho', 'auto', 'oficina-mecanica', 1101, true),
  ('Auto Elétrica', 'Automotivo', 'subnicho', 'auto', 'auto-eletrica', 1102, true),
  ('Funilaria', 'Automotivo', 'subnicho', 'auto', 'funilaria', 1103, true),
  ('Estética Automotiva', 'Automotivo', 'subnicho', 'auto', 'estetica-automotiva', 1104, true),
  ('Loja de Veículos', 'Automotivo', 'subnicho', 'auto', 'loja-de-veiculos', 1105, true),
  ('Moto Peças', 'Automotivo', 'subnicho', 'auto', 'moto-pecas', 1106, true),
  ('Rastreamento Veicular', 'Automotivo', 'subnicho', 'auto', 'rastreamento-veicular', 1107, true),
  ('Educação', 'Educação', 'grupo', 'medical', 'educacao', 1200, true),
  ('Escola', 'Educação', 'subnicho', 'medical', 'escola', 1201, true),
  ('Professor Particular', 'Educação', 'subnicho', 'medical', 'professor-particular', 1202, true),
  ('Curso Livre', 'Educação', 'subnicho', 'medical', 'curso-livre', 1203, true),
  ('Escola de Idiomas', 'Educação', 'subnicho', 'medical', 'escola-de-idiomas', 1204, true),
  ('Reforço Escolar', 'Educação', 'subnicho', 'medical', 'reforco-escolar', 1205, true),
  ('Mentor', 'Educação', 'subnicho', 'medical', 'mentor', 1206, true),
  ('Treinamento Corporativo', 'Educação', 'subnicho', 'medical', 'treinamento-corporativo', 1207, true),
  ('Imobiliário', 'Imobiliário', 'grupo', 'legal', 'imobiliario', 1300, true),
  ('Imobiliária', 'Imobiliário', 'subnicho', 'legal', 'imobiliaria', 1301, true),
  ('Corretor de Imóveis', 'Imobiliário', 'subnicho', 'legal', 'corretor-de-imoveis', 1302, true),
  ('Construtora Imobiliária', 'Imobiliário', 'subnicho', 'legal', 'construtora-imobiliaria', 1303, true),
  ('Administração de Condomínios', 'Imobiliário', 'subnicho', 'legal', 'administracao-de-condominios', 1304, true),
  ('Tecnologia', 'Tecnologia', 'grupo', 'agency', 'tecnologia', 1400, true),
  ('Software House', 'Tecnologia', 'subnicho', 'agency', 'software-house', 1401, true),
  ('SaaS', 'Tecnologia', 'subnicho', 'agency', 'saas', 1402, true),
  ('Suporte de TI', 'Tecnologia', 'subnicho', 'agency', 'suporte-de-ti', 1403, true),
  ('Automação', 'Tecnologia', 'subnicho', 'agency', 'automacao', 1404, true),
  ('Desenvolvedor', 'Tecnologia', 'subnicho', 'agency', 'desenvolvedor', 1405, true),
  ('Consultoria de Tecnologia', 'Tecnologia', 'subnicho', 'agency', 'consultoria-de-tecnologia', 1406, true)
on conflict (niche_name) do update set
  group_name = excluded.group_name,
  hero_type = excluded.hero_type,
  slug = excluded.slug,
  sort_order = excluded.sort_order,
  active = coalesce(public.niche_heros.active, excluded.active),
  theme = coalesce(public.niche_heros.theme, excluded.theme),
  updated_at = now();
