-- MIV Ecosystem V13.7 — favoritos sincronizados por conta
create table if not exists public.user_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  company_id uuid null references public.companies(id) on delete cascade,
  item_type text not null check (item_type in ('item','analysis')),
  item_id text not null,
  created_at timestamptz not null default now(),
  unique (user_id, item_type, item_id)
);

alter table public.user_favorites enable row level security;

grant select, insert, update, delete on table public.user_favorites to authenticated;
grant usage, select on sequence public.user_favorites_id_seq to authenticated;

drop policy if exists "favorites_select_own" on public.user_favorites;
create policy "favorites_select_own" on public.user_favorites for select to authenticated using (auth.uid() = user_id);

drop policy if exists "favorites_insert_own" on public.user_favorites;
create policy "favorites_insert_own" on public.user_favorites for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "favorites_update_own" on public.user_favorites;
create policy "favorites_update_own" on public.user_favorites for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "favorites_delete_own" on public.user_favorites;
create policy "favorites_delete_own" on public.user_favorites for delete to authenticated using (auth.uid() = user_id);
