const ITEM_CATALOG={whatsapp:{title:'Script inteligente de WhatsApp',unit_price:19.90,item_type:'card'}};
const send=(res,s,b)=>res.status(s).json(b);const norm=v=>({'script-whatsapp':'whatsapp','whatsapp-script':'whatsapp'}[String(v||'').trim().toLowerCase()]||String(v||'').trim().toLowerCase());
async function sbFetch(url,key,path,opt={}){return fetch(`${url}/rest/v1/${path}`,{...opt,headers:{apikey:key,'Content-Type':'application/json',...(opt.headers||{})}})}
module.exports=async function(req,res){if(req.method!=='POST')return send(res,405,{error:'Método não permitido.'});try{
 const su=process.env.SUPABASE_URL,pk=process.env.SUPABASE_PUBLISHABLE_KEY,sk=process.env.SUPABASE_SECRET_KEY;if(!su||!pk||!sk)return send(res,500,{error:'Configuração incompleta.'});
 const ah=req.headers.authorization||'',at=ah.startsWith('Bearer ')?ah.slice(7):'';if(!at)return send(res,401,{error:'Entre na sua conta para aplicar o cupom.'});const ur=await fetch(`${su}/auth/v1/user`,{headers:{apikey:pk,Authorization:`Bearer ${at}`}});if(!ur.ok)return send(res,401,{error:'Sessão inválida ou expirada.'});const user=await ur.json();
 const itemId=norm(req.body?.item_id),item=ITEM_CATALOG[itemId];if(!item)return send(res,400,{error:'Item não habilitado para pagamento.'});const originalCents=Math.round(item.unit_price*100);const code=String(req.body?.coupon_code||'').trim().toUpperCase();if(!code)return send(res,400,{error:'Digite um cupom.'});
 const cr=await sbFetch(su,sk,`coupons?code=eq.${encodeURIComponent(code)}&active=eq.true&select=*`);const rows=await cr.json();const coupon=rows?.[0];if(!coupon)return send(res,400,{error:'Cupom inválido ou inativo.'});const now=Date.now();if(coupon.starts_at&&new Date(coupon.starts_at).getTime()>now)return send(res,400,{error:'Este cupom ainda não está válido.'});if(coupon.expires_at&&new Date(coupon.expires_at).getTime()<now)return send(res,400,{error:'Este cupom expirou.'});if(coupon.item_id&&norm(coupon.item_id)!==itemId)return send(res,400,{error:'Este cupom não vale para este item.'});
 const rr=await sbFetch(su,sk,`coupon_redemptions?coupon_id=eq.${coupon.id}&select=user_id`);const reds=await rr.json();if(coupon.max_uses&&reds.length>=coupon.max_uses)return send(res,400,{error:'Este cupom atingiu o limite de usos.'});if(reds.filter(x=>x.user_id===user.id).length>=coupon.max_uses_per_user)return send(res,400,{error:'Você já utilizou este cupom.'});let discountCents=coupon.discount_type==='percent'?Math.round(originalCents*Math.min(Number(coupon.discount_value),100)/100):Math.round(Number(coupon.discount_value)*100);discountCents=Math.min(discountCents,originalCents);const finalCents=originalCents-discountCents;
 return send(res,200,{valid:true,code:coupon.code,discount_type:coupon.discount_type,discount_value:Number(coupon.discount_value),original:originalCents/100,discount:discountCents/100,amount:finalCents/100,free_unlock:finalCents===0});
}catch(e){console.error(e);return send(res,500,{error:'Não foi possível validar o cupom.'})}};
